name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # The docker login step is to prevent rate-limiting since all commands would be run as an unauthenticated or anonymous user
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # - run: docker build -t docker_cicd -f Dockerfile.dev .
      # - run: docker run -e CI=true docker_cicd npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker_single_container_deployment
          environment_name: Dockersinglecontainerdeployment-env
          region: us-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip